# Profil de deploiement

# Pour generer du SQL optimise pour Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL de la base de données via variable d'environnement
spring.datasource.url=${JDBC_URI}

# Hibernate recrée les tables au premier démarrage
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

# Spring Data REST
spring.data.rest.base-path=/api
spring.data.rest.defaultMediaType=application/json

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Forward headers pour Render
server.forward-headers-strategy=native

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:natasamba28@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from=${MAIL_USERNAME:natasamba28@gmail.com}